"""PoC generator: creates standalone Python scripts and cURL commands."""

from __future__ import annotations

import hashlib
import urllib.parse


class PoCGenerator:
    """Generates proof-of-concept artifacts for validated findings."""

    def generate(self, finding: dict) -> dict:
        """Generate Python script and cURL command for a finding."""
        url = finding.get("url", finding.get("location", ""))
        method = finding.get("method", "GET").upper()
        payload = finding.get("payload", "")
        param = finding.get("parameter", "")

        return {
            "python_script": self._python_poc(url, method, payload, param),
            "curl_command": self._curl_poc(url, method, payload, param),
            "fingerprint": self._fingerprint(finding),
        }

    def _python_poc(self, url: str, method: str, payload: str, param: str) -> str:
        if method == "GET" and param:
            test_url = f"{url}?{param}={urllib.parse.quote(payload)}" if "?" not in url else url
            base_url = f"{url}?{param}=baseline_canary" if "?" not in url else url
            return f'''#!/usr/bin/env python3
"""PoC - Auto-generated by SecAgents"""
import requests, sys

url = {repr(test_url)}
base_url = {repr(base_url)}
payload = {repr(payload)}

base_resp = requests.get(base_url, verify=False, timeout=10)
resp = requests.get(url, verify=False, timeout=10)

is_diff = resp.text != base_resp.text or resp.status_code != base_resp.status_code
is_reflected = payload in resp.text

print(f"Status: {{resp.status_code}} (Baseline: {{base_resp.status_code}})")
print(f"Response Differential Detected: {{is_diff}}")
print(f"Payload Reflected in Response: {{is_reflected}}")

# Verify real exploitation signal (response differential or payload reflection)
success = is_diff or is_reflected
sys.exit(0 if success else 1)
'''
        return f'''#!/usr/bin/env python3
"""PoC - Auto-generated by SecAgents"""
import requests, sys

url = {repr(url)}
payload = {repr(payload)}
param = {repr(param)}

base_resp = requests.post(url, data={{param: "baseline_canary"}}, verify=False, timeout=10)
resp = requests.post(url, data={{param: payload}}, verify=False, timeout=10)

is_diff = resp.text != base_resp.text or resp.status_code != base_resp.status_code
is_reflected = payload in resp.text

print(f"Status: {{resp.status_code}} (Baseline: {{base_resp.status_code}})")
print(f"Response Differential Detected: {{is_diff}}")
print(f"Payload Reflected in Response: {{is_reflected}}")

success = is_diff or is_reflected
sys.exit(0 if success else 1)
'''

    def _curl_poc(self, url: str, method: str, payload: str, param: str) -> str:
        encoded = urllib.parse.quote(payload)
        if method == "GET" and param:
            return f'curl -sk "{url}?{param}={encoded}"'
        return f'curl -sk -X POST "{url}" -d "{param}={encoded}"'

    @staticmethod
    def _fingerprint(finding: dict) -> str:
        raw = (
            f"{finding.get('title', '')}|{finding.get('location', '')}|{finding.get('payload', '')}"
        )
        return hashlib.sha256(raw.encode()).hexdigest()


class ConsensusLLM:
    """Multi-model consensus for finding verification."""

    def __init__(self, models: list[str] | None = None, min_agreement: int = 2):
        self.models = models or ["openai", "anthropic", "groq"]
        self.min_agreement = min_agreement
        self.confidence_threshold = 0.75

    async def verify(self, finding: dict, llm_fn) -> dict:
        """Send finding to multiple models, synthesize consensus."""
        votes: list[dict] = []
        for model in self.models:
            try:
                result = await llm_fn(finding, model=model)
                votes.append(
                    {
                        "model": model,
                        "valid": result.get("valid", False),
                        "confidence": result.get("confidence", 0.5),
                    }
                )
            except Exception:
                continue

        valid_votes = sum(
            1 for v in votes if v["valid"] and v["confidence"] >= self.confidence_threshold
        )
        avg_confidence = sum(v["confidence"] for v in votes) / max(len(votes), 1)

        return {
            "consensus": valid_votes >= self.min_agreement,
            "votes": votes,
            "agreement": valid_votes,
            "avg_confidence": round(avg_confidence, 3),
        }
